### ISSUE TITLE
java.lang.InternalError: Attempt to register dex file /data/user/0/com.douyu.rush/Anonymous-DexFile@3961356736.jar with multiple class loaders

### ISSUE THREAD

**Issue by stevezhou6** [Frezrik/Jiagu#10]

**Comment by Frezrik** [comment]
Maybe the app has been Jiagu。

If you want me to fix this, please tell me the following information:
1. Please send me the apk
2. Android version information of the test machine

**Comment by Frezrik** [comment]
> Same issue. @Frezrik please fix, just only need this issue fixed

Maybe the app has been Jiagu。

If you want me to fix this, please tell me the following information:

Please send me the apk
Android version information of the test machine

**Comment by Frezrik** [comment]
It is best to give an apk without Jiagu

**Comment by Frezrik** [comment]
There is a real problem with Android 11 using the app you provided. However, I found several applications by myself, and they were all fine after Jiagu. Maybe you can provide me with a demo that can reproduce this problem
