### ISSUE TITLE
android 10 多个dex的apk 加固 

### ISSUE THREAD

**Issue by guanweile** [Frezrik/Jiagu#11]
java.lang.InternalError: Attempt to register dex file /data/user/0/com.xx.xx/Anonymous-DexFile@2529934450.jar with multiple class loaders

**Comment by Frezrik** [comment]
可否提供下加固前的应用，我这边尝试了几个应用，均无法复现该问题

**Comment by guanweile** [comment]
@Frezrik  https://gitee.com/weile.com/google_pay

**Comment by Frezrik** [comment]
本项目的加固只支持5.0及以上版本。在5.0以上版本，不需要在Application里MultiDex.install(this)

**Comment by guanweile** [comment]
@Frezrik  一样 我去掉了 MultiDex.install(this)  打出的包 图标不对 也报  with multiple class loaders 错误  https://gitee.com/weile.com/google_pay

**Comment by guanweile** [comment]
帮忙指导一下

**Comment by guanweile** [comment]
@Frezrik  https://gitee.com/weile.com/demo_game 没加什么库 我测试发现 同以工程 debug可以 release不可以

**Comment by guanweile** [comment]
demo-release 加了几个库也是一样

**Comment by guanweile** [comment]
几个都是demo

**Comment by stevezhou6** [comment]
@guanweile 这个问题我解决了。

**Comment by KaLui** [comment]
> @guanweile 这个问题我解决了。

同出现这个问题，请问如何解决的？

**Comment by stevezhou6** [comment]
我这边研究了蛮久，解决了，可以有偿提供方案。

**Comment by Frezrik** [comment]
fix
https://github.com/Frezrik/Jiagu/commit/318cbfdb90a3d7575da48f8dcc1a542be2c3c0ad

**Comment by MrLiBack** [comment]
> 我这边研究了蛮久，解决了，可以有偿提供方案。

做了什么操作吗
