### ISSUE TITLE
Unreal Engine 4 unsupported

### ISSUE THREAD

**Issue by ghost** [Frezrik/Jiagu#12]
It seems Unreal Engine 4 is not supported, because after encrypt dex, I got this error "Failed to open descriptor file"

Game: Mortal Kombat mobile

![image](https://user-images.githubusercontent.com/117185724/199287058-e217f868-f42c-4147-b715-571e557509eb.png)

**Comment by Frezrik** [comment]
Maybe you can try the latest code. If the problem still exists, please paste the log and preferably provide the apk where the problem occurred
