### ISSUE TITLE
这个我去掉raw去res混淆都还说读取不到json  

### ISSUE THREAD

**Issue by guanweile** [Frezrik/Jiagu#13]
这个链接
https://gitee.com/weile.com/google_pay

/Unity: SerializationException: Invalid JSON string 
    (Filename: currently not available on il2cpp Line: -1)

**Comment by Frezrik** [comment]
看起来apk本身签名就有问题

**Comment by guanweile** [comment]
@Frezrik   我重新签名 这个apk再加固也是一样

**Comment by guanweile** [comment]
https://gitee.com/weile.com/google_pay2  这个是用你包里的testkey签名的

**Comment by guanweile** [comment]
@Frezrik  知道什么原因了  是没有动态加载 游戏的Application  你的这个壳  需要指向游戏的Application  因为游戏的apk有可能需要Application做一些处理

**Comment by Frezrik** [comment]
有重走源应用application的生命周期的

**Comment by guanweile** [comment]
@Frezrik  这个关闭一下  我这边的原因      谢谢
