### ISSUE TITLE
资源问题

### ISSUE THREAD

**Issue by stevezhou6** [Frezrik/Jiagu#6]
修复raw资源出错 commit
if ("resources.arsc".equals(file.getName()) || file.getAbsolutePath().contains(File.separator + "raw" + File.separator)) {
这个修改是什么意思

**Comment by Frezrik** [comment]
> 修复raw资源出错 commit if ("resources.arsc".equals(file.getName()) || file.getAbsolutePath().contains(File.separator + "raw" + File.separator)) { 这个修改是什么意思

https://blog.csdn.net/z9722/article/details/119964337
